import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="relative z-10">{children}</div>

        {/* Decorative rocket animation overlay */}
        <div className="rocket-sky" aria-hidden="true">
          <span className="rocket r1">🚀</span>
          <span className="rocket r2">🚀</span>
          <span className="rocket r3">🚀</span>
          <span className="rocket r4">🚀</span>
        </div>
      </body>
    </html>
  );
}
